#!/bin/bash

# Requires playerctl binary to be in your path (except cmus)
# See: https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session).

metadata=""
player_arg=$1

# If the player name has not been specified as an argument,
# check out media players that are currently open and running,
# and try to find any that matches the given list of audio players.
if [ -z $player_arg ]; then
	# Get all currently running players
    all_players=$(playerctl -l)
	# Magic...
	if [[ $all_players =~ (X rhythmbox|spotify|vlc|audacious|xmms2|mplayer {2})$ ]]; then
		# 'player_args' will become one of the given players, if it was found in the 'all_players' string
    	player_arg=${BASH_REMATCH[1]}
	else
		exit 0
	fi
fi

#For 'playerctl' the player argument must be as '--player=audacious'
player_arg="--player=$player_arg";

# Mouse button clicks on current track text
case $BLOCK_BUTTON in
	1) playerctl $player_arg previous;;		# left mouse button
	2) playerctl $player_arg play-pause;;	# middle button click
	3) playerctl $player_arg next;;			# right button click
esac

artist=$(playerctl $player_arg metadata artist)
if [ ! -z "$artist" ]; then
	metadata=$artist
fi

title=$(playerctl $player_arg metadata title)
if [ ! -z "$title" ]; then
	metadata=$metadata' - '$title
fi

echo $metadata

exit 0
